version: "3"

volumes:
  anvil_data:

services:
  app:
    environment:
      - ANVIL_LABS_PATH=${ANVIL_LABS_PATH}
    image: ghcr.io/anvilistas/anvil-labs-integration-tests/app:latest
    volumes:
      - ./anvil_extras:/anvil_extras
      - ${ANVIL_LABS_PATH}:/anvil_labs
    command: anvil-app-server --config-file config.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
  test_runner:
    image: ghcr.io/anvilistas/anvil-labs-integration-tests/test_runner:latest
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./tests:/code/tests
    command: python -m pytest
