version: "3"

volumes:
  anvil_data:

services:
  anvil:
    environment:
      - ANVIL_LABS_PATH=${ANVIL_LABS_PATH}
    image: ghcr.io/anvilistas/anvil-labs-integration-tests:latest
    ports:
      - 3030:3030
    volumes:
      - ./anvil_extras:/anvil_extras
      - ${ANVIL_LABS_PATH}:/anvil_labs
    command: anvil-app-server --config-file anvil-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
