version: "3"

volumes:
  postgres:

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=anvil
      - POSTGRES_DB=anvil
      - POSTGRES_PASSWORD=anvil
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anvil"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    environment:
      - ANVIL_LABS_PATH=${ANVIL_LABS_PATH}
    image: ghcr.io/anvilistas/anvil-labs-integration-tests/app:latest
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "3030:3030"
    volumes:
      - ./anvil_extras:/anvil_extras
      - ${ANVIL_LABS_PATH}:/anvil_labs
    command: anvil-app-server --config-file config.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  test_runner:
    image: ghcr.io/anvilistas/anvil-labs-integration-tests/test_runner:latest
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./tests:/code/tests
    command: python -m pytest
